federation_version: 2
subgraphs:
  users:
    routing_url: http://localhost:4001
    schema:
      file: ./schema/users-schema.graphql
  posts:
    routing_url: http://localhost:4002
    schema:
      file: ./schema/posts-schema.graphql
